name: Manual

on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        defalut: Hello
        required: true
        description: A cheerful word

jobs:
  run:
    runs-on: ubuntu-latesßt
    steps:
      - run: echo "${{ inputs.greeting}}"
